from django.contrib import admin
import models 

# Register your models here.

admin.site.register(models.LXF)

admin.site.register(models.UserAccount)
admin.site.register(models.Meet_MeetManager)
admin.site.register(models.Event_MeetManager)
admin.site.register(models.Constructor_MeetManager)
admin.site.register(models.Contact_Constructor_MeetManager)
admin.site.register(models.Contact_Meet_MeetManager)
admin.site.register(models.Pool_MeetManager)
admin.site.register(models.Facility_MeetManager)
admin.site.register(models.PointTable_MeetManager)
admin.site.register(models.Session_MeetManager)
admin.site.register(models.SwimStyle_MeetManager)
admin.site.register(models.AgeGroup_MeetManager)
admin.site.register(models.Fee_MeetManager)
admin.site.register(models.AgeDate_MeetManager)
##### Team Manager ####
admin.site.register(models.Constructor_TeamManager)
admin.site.register(models.Contact_Constructor_TeamManager)
admin.site.register(models.Meet_TeamManager)
admin.site.register(models.Qualify_TeamManager)
admin.site.register(models.Pool_TeamManager)
admin.site.register(models.AgeDate_TeamManager)
admin.site.register(models.Session_TeamManager)
admin.site.register(models.Event_TeamManager)
admin.site.register(models.SwimStyle_TeamManager)
admin.site.register(models.Fee_TeamManager)
admin.site.register(models.AgeGroup_TeamManager)
admin.site.register(models.Club_TeamManager)
admin.site.register(models.Athlete_TeamManager)
admin.site.register(models.Entry_Athlete_TeamManager)
admin.site.register(models.MeetInfo_Entry_Athlete_TeamManager)
admin.site.register(models.Relay_TeamManager)
admin.site.register(models.Entry_Relay_TeamManager)
admin.site.register(models.RelayPosition_TeamManager)
admin.site.register(models.MeetInfo_RelayPosition_TeamManager)
