# Generated by Django 4.1.9 on 2024-01-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lxf',
            name='meet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easyswimapp.meet_meetmanager'),
        ),
    ]
