# Generated by Django 4.1.9 on 2024-01-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lxf',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
