# Generated by Django 4.1.9 on 2024-01-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='daytime',
            field=models.TimeField(null=True),
        ),
    ]
