# Generated by Django 4.1.9 on 2024-01-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet_meetmanager',
            name='teams',
            field=models.ManyToManyField(related_name='meets', to='easyswimapp.meet_teammanager'),
        ),
    ]
