# Generated by Django 4.1.9 on 2024-01-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0002_alter_event_daytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='handicap',
            field=models.IntegerField(),
        ),
    ]
