# Generated by Django 4.1.9 on 2024-01-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0002_lxf_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet_meetmanager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
