# Generated by Django 4.1.9 on 2024-01-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0003_meet_meetmanager_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet_meetmanager',
            name='maxentriesathlete',
            field=models.IntegerField(null=True),
        ),
    ]
