# Generated by Django 4.1.9 on 2024-01-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0003_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='default_username', max_length=255, unique=True),
        ),
    ]
