# Generated by Django 4.1.9 on 2024-01-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0004_alter_meet_meetmanager_maxentriesathlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_meetmanager',
            name='maxentriesathlete',
            field=models.IntegerField(null=True),
        ),
    ]
