# Generated by Django 4.1.9 on 2024-01-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0005_alter_session_meetmanager_maxentriesathlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup_meetmanager',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
