# Generated by Django 4.1.9 on 2024-01-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyswimapp', '0006_alter_agegroup_meetmanager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet_meetmanager',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
