name: Build HTML

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend/docs

    - name: Run make html
      run: |
        sphinx-build -b html ./source ./build 
        git commit -m "Update HTML documentation" --author="GitHub Actions <actions@github.com>"
        git push
      working-directory: backend/docs
