name: Build HTML and Auto-commit
permissions:
  contents: write
on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend/docs

    - name: Run make html
      run: |
        sphinx-build -b html ./source ./build 
      working-directory: backend/docs

    - name: Commit changes
      run: |
        git config --global user.name 'Jose Pedro Aguiar'
        git config --global user.email '88104767+josePedroAguiar@users.noreply.github.com.'
        git add .
        git commit -m "Automated report" -m "Commit details here"

    - name: Push changes to a new branch
      run: |
        git branch automated-update-branch
        git checkout automated-update-branch
        git push origin automated-update-branch

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Add automated report
        committer: Jose Pedro Aguiar <88104767+josePedroAguiar@users.noreply.github.com>
        body: |
          Automated report
          - Contains updated documentation
        title: 'Automated Documentation Update'
        labels: documentation, automated pr
